import React from 'react'
import { Callout, Term } from '../../components/ui.jsx'

const OUT = [
  ['p', "prompt (10 tokens): 'Alan Turing theorized that computers would one day become'"],
  "ids: [36235, 39141, 18765, 1143, 326, 9061, 561, 530, 1110, 1716]",
  '',
  "[naive]  continuation=' the most powerful machines on the planet.'   total=842 ms",
  "[cached] continuation=' the most powerful machines on the planet.'",
  '         prefill=72 ms  then decode steps: min=26 ms  max=29 ms  mean=27 ms',
  '         decode total=218 ms vs naive 842 ms -> 3.9x less work on this tiny prompt',
  '',
  'max |logits_cached - logits_naive| over 8 decode steps: 1.678e-04',
  ['p', '   (nonzero is expected — see the note below)'],
  'cache after generation: 18 rows x 12 layers = 1,327,104 bytes (1,296 KiB)',
  'KV cost per token: 73,728 bytes FP32 (36,864 bytes FP16/BF16 like engines)',
  'weight-GEMM FLOPs: naive 26.88 GFLOP vs cached 4.48 GFLOP (6.0x saved)',
  '',
  ['ok', 'CHECKSUM: PASS -- cache is behaviorally invisible; it only removes waste.'],
]

export default function S3_Checksum() {
  return (
    <>
      <h2 id="checksum">The golden checksum — now on the cached path</h2>
      <p className="sub">
        Day 3's checksum validated the <em>math</em>. Today it does a second job: prove the
        <em> cache</em> does not change behavior. Same prompt, same 8 greedy tokens, generated by a
        completely different execution path (prefill + single-token decodes instead of 8 full
        forwards):
      </p>
      <Term title="code/01_naive_vs_cached.py — verified output" lines={OUT} />

      <h3>Why the logits differ by 1.7e-4 — and why that's fine</h3>
      <p>
        The naive path computes GEMMs shaped <code className="inline">(18, 768) × (768, 2304)</code>;
        the cached decode computes <code className="inline">(1, 768) × (768, 2304)</code>. BLAS picks
        different kernels and <strong>different summation orders</strong> for different shapes, and
        float addition is not associative — so the last bits wobble (~1e-6 relative on logits of
        magnitude ~100). The argmax never moved in 8 steps.
      </p>
      <Callout kind="disc" title="The contract, stated precisely">
        A correct KV cache guarantees <strong>token identity under greedy decoding</strong> and
        logit drift within float-reorder noise — <em>not</em> bitwise identity. Every optimization from
        now on (paging, batching, FP16 KV, fused kernels, Day 5's server) is held to this same
        contract: <strong>the golden continuation must come back unchanged.</strong>
      </Callout>
      <div className="divider" />
    </>
  )
}
